//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzMotorsport.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class joueur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public joueur()
        {
            this.quizzs = new HashSet<quizz>();
        }
    
        public short idjoueur { get; set; }
        public string pseudo { get; set; }
        public Nullable<decimal> pourcentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quizz> quizzs { get; set; }
    }
}
