//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzMotorsport.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quizzmotorsportEntities : DbContext
    {
        public quizzmotorsportEntities()
            : base("name=quizzmotorsportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<joueur> joueurs { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<quizz> quizzs { get; set; }
        public virtual DbSet<response> responses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
